### ISSUE TITLE
Prepare code for publish

### ISSUE THREAD

**Issue by as-ajitsingh** [bored-engineers/commentinator#8]
**Tasks -**
- [ ] Update Readme, add code related to unpkg and next js
- [ ] Update package.json
- [ ] Improve Sample Code
- [ ] Add Github Actions
- [ ] Unit and e2e tests
